version: '2'
services:
    web:
        build: .
        ports:
            - "80:3000"
        depends_on:
            - geth
    geth:
        build:
            context: .
            dockerfile: Dockerfile-geth
        env_file: .env
        ports:
            - "8545:8545"
            - "30303:30303"
        volumes:
            - /Users/zoolander/Library/Ethereum:/root/.ethereum
    swarm:
        build:
            context: .
            dockerfile: Dockerfile-swarm
        env_file: .env
        ports:
            - "8500:8500"
            - "30399:30399"
        volumes:
            - /Users/zoolander/Library/Ethereum:/root/.ethereum
        depends_on:
            - geth
        tty: true
