version: '2'
services:
    web:
        build: .
        ports:
            - "80:3000"
        depends_on:
            - geth
    geth:
        build:
            context: .
            dockerfile: Dockerfile-geth
        environment:
            - KEYFILE="0da56c5b3240966a5538716b19382ac3ac71198d2d9a009b5647da6514150116"
            - PASSWORDFILE=testpass
        ports:
            - "8545:8545"
            - "30303:30303"
        volumes:
            - /Users/zoolander/ethereum:/root
        entrypoint: geth --fast --cache=512 --rpc --rpcaddr=geth
    swarm:
        build:
            context: .
            dockerfile: Dockerfile-swarm
        environment:
            - BZZACCOUNT=0xb048a8bb2f7D2c3FDe00f6F65aB6e5E72593d86E
        tty: true
