version: '2'
services:
    web:
        build: .
        ports:
            - "80:3000"
        depends_on:
            - geth
    geth:
        image: ethereum/client-go
        ports:
            - "8545:8545"
            - "30303:30303"
        volumes:
            - /Users/zoolander/ethereum:/root
        entrypoint: geth --fast --cache=512 --rpc --rpcaddr=geth
    swarm:
        build:
            context: .
            dockerfile: Dockerfile-swarm
        environment:
            - BZZKEY=dogeroni
        tty: true
